name: construct
dependencies:
- decorator=4.0.4=py35_0
- ipython=4.0.0=py35_0
- ipython_genutils=0.1.0=py35_0
- jdcal=1.0=py35_0
- libgfortran=1.0=0
- libxml2=2.9.2=0
- libxslt=1.1.28=0
- lxml=3.4.4=py35_0
- networkx=1.10=py35_0
- numpy=1.10.1=py35_0
- openblas=0.2.14=3
- openpyxl=2.2.6=py35_0
- openssl=1.0.2d=0
- path.py=8.1.2=py35_0
- pexpect=3.3=py35_0
- pickleshare=0.5=py35_0
- pip=7.1.2=py35_0
- python=3.5.0=1
- readline=6.2=2
- scipy=0.16.0=np110py35_1
- setuptools=18.4=py35_0
- simplegeneric=0.8.1=py35_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- traitlets=4.0.0=py35_0
- wheel=0.26.0=py35_1
- xz=5.0.5=0
- zlib=1.2.8=0
- pip:
  - cairocffi==0.7.2
  - connectome-utils==0.0.0
  - cycler==0.9.0
  - ipython-genutils==0.1.0
  - matplotlib==1.5.0
  - nose==1.3.7
  - ptyprocess==0.5
  - pycparser==2.14
  - pyparsing==2.0.5
  - python-dateutil==2.4.2
  - pytz==2015.7
  - six==1.10.0
  - virtualenv==13.1.2

