#!/bin/bash
echo Constructing physical network...
python3 -m construct_physical
echo Constructing extrasynaptic network...
python3 -m construct_extrasyn
echo Constructing metadata...
python3 -m construct_metadata
echo Combining...
python3 -m combine
echo Finished! Output in ./combine/tgt_data